### ISSUE TITLE
BUG: property description must be an ob... (in <>.reply() > mergeBody)

### ISSUE THREAD

**Issue by GulimjaVT** [typicalninja493/tweets.ts#1]
When doing tweets.reply() on an event emitter, I get this error: 
![image](https://user-images.githubusercontent.com/63856100/162573599-5ecb5329-9d2e-48b0-92f4-75cf43c40448.png)
Please either fix this or let me know how to fix this myself^^
Thank you

**Comment by typicalninja** [comment]
Will take a look tmr, since its midnight here, is that  okay? If  possible minimal code example to get this error (since i didnt get this bug in dev suspecting somethin wrong in passed args)
thanks

**Comment by GulimjaVT** [comment]
stream.on("tweet", (tweet) => {
   tweet.reply("text").then(tweet2 => {
      console.log(tweet2.url)
   }.catch((err) => {
      console.log(err)
   }
}

**Comment by typicalninja** [comment]
Seems like nothing wrong there, ill check tmr on my code samples
